#!/usr/bin/env bash

DEFAULT_SHELL="go"

GIT_WORKSPACE="$(git rev-parse --show-toplevel)"
APP_NAME=$(basename "$GIT_WORKSPACE")
WORKSPACE="${GIT_WORKSPACE}/vscode-iaac"

CONFIG_DIR="${WORKSPACE}/${DEFAULT_SHELL}/.devcontainer"
debug "CONFIG_DIR : $CONFIG_DIR"
CONFIG_FILE="devcontainer.json"
DOCKER_IMAGE="vsc-$APP_NAME:$(git rev-parse HEAD)"
debug "DOCKER_IMAGE : $DOCKER_IMAGE"

DEV_CONTAINER_JSON_PATH="$CONFIG_DIR/$CONFIG_FILE"
debug "DEV_CONTAINER_JSON_PATH : $DEV_CONTAINER_JSON_PATH"

export SHELL_TYPE  GIT_WORKSPACE APP_NAME WORKSPACE
export CONFIG_DIR CONFIG_FILE DOCKER_IMAGE
export DEV_CONTAINER_JSON_PATH