name: CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
  
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Container
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./ci-shell/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          tags:  ${{ secrets.DOCKERHUB_USERNAME }}/ci-shell:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: IaaC Test Docker Image
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/ci-shell:latest
          run: shellspec -c ci-shell/spec --tag unit,integration,iaac --kcov

        
