name: Go

on:
  push:
    branches: [ main ]

jobs:

  go:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
  
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Container
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./vscode-iaac/go/.devcontainer
          file: ./vscode-iaac/go/.devcontainer/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          tags:  ${{ secrets.DOCKERHUB_USERNAME }}/go-vsc:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true

      - name: IaaC Test Go Dev Container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/go-vsc:latest
          run: |
            git clone https://github.com/rajasoun/ci-shell-iaac
            cd ci-shell-iaac
            ci-shell/dev_container.sh e2e -d go

