name: SFDX

on:
  push:
    branches: [ main ]

jobs:

  sfdx:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
  
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: IaaC Test Go Dev Container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/ci-shell:latest
          options: --name ci-shell --hostname ci-shell -v "$(pwd):$(pwd)" -v ${{ github.workspace }}:/workspaces -v /var/run/docker.sock:/var/run/docker.sock  -w "$(pwd)"
          run: |
            ci-shell/dev_container.sh build -d sfdx
            # ci-shell/dev_container.sh e2e -d sfdx
