name: SFDX

on:
  push:
    branches: [ main ]

jobs:

  sfdx:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
  
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Container
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./vscode-iaac/sfdx
          file: ./vscode-iaac/sfdx/.devcontainer/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          tags:  ${{ secrets.DOCKERHUB_USERNAME }}/sfdx-vsc:latest
          push: true
