name: CI

on:
  push:
    branches: [ main ]

jobs:
    test-docker:
      runs-on: ubuntu-latest
    container:
      image: ${{ secrets.DOCKERHUB_USERNAME }}/ci-shell:latest
    steps:
         - name: Shell Spec Unit Test
           run: |
             shellspec -c ci-shell/spec --tag unit,integration,iaac --kcov